service: go-servers

image: hendry/go-servers

registry:
  username: hendry
  password:
    - KAMAL_REGISTRY_PASSWORD

servers:
  web:
    - 81.187.180.178

builder: # raspberry pi 5
  arch: aarch64

ssh:
  user: hendry

proxy:
  app_port: 8080
